### ISSUE TITLE
NOT an issue but read

### ISSUE THREAD

**Issue by CrypticKingJoe** [TheSph1nx/RT-101#2]
Unsure if I posted already but I have to say I really like this project coming along as it does
now we just need a splashscreen similar to nanocore's as I was never able to replicate it 
the rotating logo is my main goal but well I am not the best at VB

**Comment by TheSph1nx** [comment]
Yes the main purpose was that, for the logo i've already created it but putting it on will be too much similar to nanocore ... this wants to be a rude and fast to use rat. But you got the source pull up something if you want.

**Comment by CrypticKingJoe** [comment]
that would be awesome to have it 
would you like to email me it or are you going to publicly post it?

**Comment by TheSph1nx** [comment]
Well this project now it's done and i don't think I'll keep working on this, now I'm currently working on new one but I repeat if you want you can try to do something.

**Comment by CrypticKingJoe** [comment]
ah I dont know how to even start with the logo sadly so I will just leave it as is
