### ISSUE TITLE
Stub source code?

### ISSUE THREAD

**Issue by DeltaLinkECL** [TheSph1nx/RT-101#3]
Can you please add the stub source code? I know this may not seem like a big deal, but I want to add features and stuff and need the stub source to do so.

**Comment by TheSph1nx** [comment]
In the following days I'll upload the source for the stub ! Promise !

**Comment by MaxTrima** [comment]
THANK YOU BRO !

**Comment by TheSph1nx** [comment]
No problem guys ! I didn't published that before just to avoid ripping, hoped someone tried to create a crypter only using the final exe, but who cares in this week / weekend I'm going to publish the source... before I have to clean it.

**Comment by TheSph1nx** [comment]
Uploaded stub guys.. closing this one.
