### ISSUE TITLE
i have a promplem with trat , i have  1 client connected but it doesn't show up on the list view

### ISSUE THREAD

**Issue by CyberSecII** [TheSph1nx/RT-101#7]
I have a problem with TRAT , I have  1 client connected but it doesn't show up on the list view.
I checked the port and the password if it is ok and it seems to be ok.
How can I fix this? Can you please check and fix it? by the way, thank you for this great tutorial on youtube you are the reason why I started coding VB

**Comment by TheSph1nx** [comment]
This could be the firewall that doesn't allow the connection or be sure to restart the server once you changed the password... otherwise try to set some breakpoints and debug the entire project.
